# Defines the C compiler
CC := gcc

# C standard
STANDARD := -std=c99

# Specifies to GCC the required warnings
WARNS := -Wall -Wextra -pedantic # -pedantic warns on language standards

# Debug flags (add to CFLAGS if you wish to compile the program for debug purposes)
DEBUG := -g -fsanitize=address 

# Flags for compiling
CFLAGS := $(STACK) $(WARNS)

# Binary name
BINARY := ultimate-ttt.exe

# Files
FILES := main.c ./options/options.c ./person/person.c ./room/room.c ./utils/utils.c ./verificar/verificar.c ./simulation/simulation.c

default: all

help:
	@echo "	   all		- Compiles and generates binary files"
	@echo "	   debug	- Compiles and generates binary files for debugging"
	@echo "    clean    - Clean the project by removing binaries"
	@echo "    help     - Prints a help message with target rules"

all: $(FILES)
	$(CC) -o $(BINARY) $^ $(CFLAGS)

debug: $(FILES)
	$(CC) -o $(BINARY) $^ $(CFLAGS) $(DEBUG)

clean:
	rm $(BINARY)